services:
  db:
    image: postgres:16
    container_name: lbwl_db
    environment:
      POSTGRES_USER: lbwl_user
      POSTGRES_PASSWORD: lbwl_pass
      POSTGRES_DB: lbwl
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lbwl_user -d lbwl"]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    build: ./scraper
    container_name: lbwl_scraper
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: lbwl
      DB_USER: lbwl_user
      DB_PASSWORD: lbwl_pass
    command: ["python", "main.py"]
    # on laissera le script vide / neutre tant qu'on n'a pas cod√© le scraper

volumes:
  db_data:
