services:
  db:
    image: postgres:16
    container_name: lbwl_db
    environment:
      POSTGRES_USER: lbwl_user
      POSTGRES_PASSWORD: lbwl_pass
      POSTGRES_DB: lbwl
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lbwl_user -d lbwl"]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    build: ./scraper
    container_name: lbwl_scraper
    volumes:
      - ./scraper:/app
      - ./football_data:/football_data
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: lbwl
      DB_USER: lbwl_user
      DB_PASSWORD: lbwl_pass
      FOOTBALL_DATA_API_KEY: 947ede5d58494469ac06930f5d37acb2
      NBA_START_GAME_ID: '0020400002'
    command: ["python", "main.py"]
    # on laissera le script vide / neutre tant qu'on n'a pas cod√© le scraper

  lbwl_explorer:
    build:
      context: ./explorer
    container_name: lbwl_explorer
    volumes:
      - ./explorer:/app
    environment:
      DB_HOST: lbwl_db
      DB_PORT: 5432
      DB_NAME: lbwl
      DB_USER: lbwl_user
      DB_PASSWORD: lbwl_pass
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8501:8501"
    restart: unless-stopped

  lbwl_api:
    build:
      context: ./api
    container_name: lbwl_api
    volumes:
      - ./api:/app/api
      - ./db:/app/db:ro
    environment:
      DB_HOST: lbwl_db
      DB_PORT: 5432
      DB_NAME: lbwl
      DB_USER: lbwl_user
      DB_PASSWORD: lbwl_pass
      API_MAX_ROWS: 5000
      NLP_AUTO_INDEX: 1
      OPENAI_MODEL: gpt-4o-mini
      OPENAI_API_KEY: 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
      NLP_MODEL_NAME: sentence-transformers/all-MiniLM-L6-v2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped



volumes:
  db_data:
